name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Install build tools
      run: go get -u github.com/vektra/mockery/cmd/mockery

    - name: Build
      run:  |
        go generate ./...
        go build -v ./...

    - name: Vet
      run: go vet ./...

    - name: Test
      run: go test -v ./...
